#!/usr/bin/env bash
# =============================================================================
# tfx-codex-swarm: Selective Spawn Commands
# Generated by: tfx-codex-swarm skill (Steps 5-8)
# Date: 2026-03-30
# Target issues: #24 (remote-spawn-file-transfer), #28 (headless-guard-spawn-deadlock)
# Profile: codex53_xhigh (user override)
# OMX Skill: $ralph (user override)
# =============================================================================
# WARNING: This script is a DRY RUN artifact. Do NOT execute directly.
# =============================================================================

PROJECT_ROOT="C:/Users/SSAFY/Desktop/Projects/cli/triflux"
BASH_EXE='C:\Program Files\Git\bin\bash.exe'

# ─────────────────────────────────────────────────────────────────────────────
# Step 5: Worktree Creation
# ─────────────────────────────────────────────────────────────────────────────

# Issue #24 — worktree
git worktree add "${PROJECT_ROOT}/.codex-swarm/wt-issue-24" -b codex/issue-24 2>/dev/null || \
git worktree add "${PROJECT_ROOT}/.codex-swarm/wt-issue-24" codex/issue-24

# Issue #28 — worktree
git worktree add "${PROJECT_ROOT}/.codex-swarm/wt-issue-28" -b codex/issue-28 2>/dev/null || \
git worktree add "${PROJECT_ROOT}/.codex-swarm/wt-issue-28" codex/issue-28

# ─────────────────────────────────────────────────────────────────────────────
# Step 6: Prompt Generation
# ─────────────────────────────────────────────────────────────────────────────

mkdir -p "${PROJECT_ROOT}/.codex-swarm/prompts"

# --- Prompt for Issue #24 ---
cat > "${PROJECT_ROOT}/.codex-swarm/prompts/prompt-24.md" << 'PROMPT_24'
triflux 프로젝트의 태스크를 구현해야 합니다.

태스크 파일을 먼저 읽으세요: .omx/plans/prd-issue-24-remote-spawn-file-transfer.md

작업 순서:
1. 태스크 파일을 읽고 요구사항을 파악하세요
2. $ralph 스킬을 사용하세요 — 계획 수립 후 완료까지 반복 실행합니다. 작업이 완전히 끝날 때까지 멈추지 마세요.
3. 모든 acceptance criteria를 충족하는지 검증하세요
4. npm test로 기존 테스트가 깨지지 않았는지 확인하세요

프로젝트 정보:
- triflux: Claude Code용 멀티모델 CLI 오케스트레이터
- 언어: JavaScript/ESM (Node.js), 테스트: npm test
PROMPT_24

# Copy PRD into worktree
cp "${PROJECT_ROOT}/.omx/plans/prd-issue-24-remote-spawn-file-transfer.md" \
   "${PROJECT_ROOT}/.codex-swarm/wt-issue-24/.omx/plans/prd-issue-24-remote-spawn-file-transfer.md"

# --- Prompt for Issue #28 ---
cat > "${PROJECT_ROOT}/.codex-swarm/prompts/prompt-28.md" << 'PROMPT_28'
triflux 프로젝트의 태스크를 구현해야 합니다.

태스크 파일을 먼저 읽으세요: .omx/plans/prd-issue-28-headless-guard-spawn-deadlock.md

작업 순서:
1. 태스크 파일을 읽고 요구사항을 파악하세요
2. $ralph 스킬을 사용하세요 — 계획 수립 후 완료까지 반복 실행합니다. 작업이 완전히 끝날 때까지 멈추지 마세요.
3. 모든 acceptance criteria를 충족하는지 검증하세요
4. npm test로 기존 테스트가 깨지지 않았는지 확인하세요

프로젝트 정보:
- triflux: Claude Code용 멀티모델 CLI 오케스트레이터
- 언어: JavaScript/ESM (Node.js), 테스트: npm test
PROMPT_28

# Copy PRD into worktree
cp "${PROJECT_ROOT}/.omx/plans/prd-issue-28-headless-guard-spawn-deadlock.md" \
   "${PROJECT_ROOT}/.codex-swarm/wt-issue-28/.omx/plans/prd-issue-28-headless-guard-spawn-deadlock.md"

# ─────────────────────────────────────────────────────────────────────────────
# Step 7: psmux Session Creation + Codex Launch
# ─────────────────────────────────────────────────────────────────────────────

# Common Codex flags (codex53_xhigh profile)
PROFILE_FLAGS="-c 'model=\"gpt-5.3-codex\"' -c 'model_reasoning_effort=\"xhigh\"'"

# --- Issue #24 session ---
psmux new-session \
  --name "codex-swarm-24" \
  --dir "${PROJECT_ROOT}/.codex-swarm/wt-issue-24"

psmux send-keys --target "codex-swarm-24:0" \
  "codex -c 'model=\"gpt-5.3-codex\"' -c 'model_reasoning_effort=\"xhigh\"' --full-auto \"\$(cat ${PROJECT_ROOT}/.codex-swarm/prompts/prompt-24.md)\"" Enter

# --- Issue #28 session ---
psmux new-session \
  --name "codex-swarm-28" \
  --dir "${PROJECT_ROOT}/.codex-swarm/wt-issue-28"

psmux send-keys --target "codex-swarm-28:0" \
  "codex -c 'model=\"gpt-5.3-codex\"' -c 'model_reasoning_effort=\"xhigh\"' --full-auto \"\$(cat ${PROJECT_ROOT}/.codex-swarm/prompts/prompt-28.md)\"" Enter

# ─────────────────────────────────────────────────────────────────────────────
# Step 8: WT Tab Batch Attach
# ─────────────────────────────────────────────────────────────────────────────

# Primary method: psmux attach
psmux attach --session "codex-swarm-24" --wt-new-window
psmux attach --session "codex-swarm-28" --wt-tab

# Fallback: wt.exe direct (if psmux attach unavailable)
# wt.exe -w new \
#   --title "issue-24: file-transfer" \
#   -d "${PROJECT_ROOT}/.codex-swarm/wt-issue-24" \
#   "$BASH_EXE" -c "psmux attach codex-swarm-24" \; \
#   new-tab \
#   --title "issue-28: guard-deadlock" \
#   -d "${PROJECT_ROOT}/.codex-swarm/wt-issue-28" \
#   "$BASH_EXE" -c "psmux attach codex-swarm-28"

# ─────────────────────────────────────────────────────────────────────────────
# Status Report (Step 9 — would be displayed after spawn)
# ─────────────────────────────────────────────────────────────────────────────
# | # | Task                       | Type     | OMX Skill | Profile        | Worktree      | Session         |
# |---|----------------------------|----------|-----------|----------------|---------------|-----------------|
# | 24 | remote-spawn-file-transfer | implement | $ralph   | codex53_xhigh | wt-issue-24   | codex-swarm-24  |
# | 28 | headless-guard-deadlock    | implement | $ralph   | codex53_xhigh | wt-issue-28   | codex-swarm-28  |
