// @triflux/remote — barrel export (auto-generated by pack.mjs)
// Team
export { orchestrate, decomposeTask, buildLeadPrompt, buildPrompt } from './team/orchestrator.mjs';
export { createPsmuxSession, startCapture } from './team/psmux.mjs';
