// @triflux/remote — barrel export (auto-generated by pack.mjs)
// Server

// Pipe
export { createPipeServer, getPipePath } from "./pipe.mjs";
export { getHubInfo, getOrCreateServer, startHub } from "./server.mjs";
// Store
export { createStoreAdapter } from "./store-adapter.mjs";
export { createConductor } from "./team/conductor.mjs";
// Team
export {
  buildLeadPrompt,
  buildPrompt,
  decomposeTask,
  orchestrate,
} from "./team/orchestrator.mjs";
export { createPsmuxSession, startCapture } from "./team/psmux.mjs";
export {
  createSwarmHypervisor,
  SWARM_STATES,
} from "./team/swarm-hypervisor.mjs";
// Swarm
export { createSwarmLocks } from "./team/swarm-locks.mjs";
export {
  buildFileLeaseMap,
  buildMcpManifest,
  computeMergeOrder,
  parseShards,
  planSwarm,
} from "./team/swarm-planner.mjs";
export {
  buildRedundantIds,
  reconcile,
  shouldRunRedundant,
} from "./team/swarm-reconciler.mjs";
export {
  ensureWorktree,
  fetchRemoteShard,
  prepareIntegrationBranch,
  pruneWorktree,
  rebaseShardOntoIntegration,
} from "./team/worktree-lifecycle.mjs";
