// @triflux/remote — barrel export (auto-generated by pack.mjs)
// Server
export { startHub, getHubInfo, getOrCreateServer } from './server.mjs';

// Store
export { createStoreAdapter } from './store-adapter.mjs';

// Pipe
export { createPipeServer, getPipePath } from './pipe.mjs';

// Team
export { orchestrate, decomposeTask, buildLeadPrompt, buildPrompt } from './team/orchestrator.mjs';
export { createPsmuxSession, startCapture } from './team/psmux.mjs';
export { createConductor } from './team/conductor.mjs';

// Swarm
export { createSwarmLocks } from './team/swarm-locks.mjs';
export { parseShards, buildFileLeaseMap, buildMcpManifest, computeMergeOrder, planSwarm } from './team/swarm-planner.mjs';
export { createSwarmHypervisor, SWARM_STATES } from './team/swarm-hypervisor.mjs';
export { reconcile, buildRedundantIds, shouldRunRedundant } from './team/swarm-reconciler.mjs';
export { ensureWorktree, prepareIntegrationBranch, rebaseShardOntoIntegration, pruneWorktree, pruneOrphanWorktrees, fetchRemoteShard } from './team/worktree-lifecycle.mjs';
