#!/usr/bin/env node
// scripts/pack.mjs — 패키지 조립 스크립트
// 소스 파일을 packages/*/에 복사하여 npm publish 준비.
//
// Usage: node scripts/pack.mjs [core|remote|triflux|all]

import { cpSync, existsSync, mkdirSync, rmSync, readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname, relative, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));

// ── 파일 매핑: 패키지별로 어떤 소스 파일이 포함되는지 ──────────

const CORE_FILES = [
  // hub root — core modules
  'hub/cli-adapter-base.mjs',
  'hub/codex-adapter.mjs',
  'hub/codex-compat.mjs',
  'hub/codex-preflight.mjs',
  'hub/gemini-adapter.mjs',
  'hub/team-bridge.mjs',
  'hub/paths.mjs',
  'hub/platform.mjs',
  'hub/state.mjs',
  'hub/intent.mjs',
  'hub/token-mode.mjs',
  'hub/router.mjs',
  'hub/hitl.mjs',
  'hub/assign-callbacks.mjs',
  'hub/fullcycle.mjs',
  'hub/bridge.mjs',
  'hub/reflexion.mjs',
  'hub/research.mjs',
  'hub/session-fingerprint.mjs',
  // Neural Memory (Lake 2 Phase 1)
  'hub/adaptive.mjs',
  'hub/adaptive-diagnostic.mjs',
  'hub/adaptive-inject.mjs',
  'hub/adaptive-memory.mjs',
  'hub/memory-doctor.mjs',
  'hub/account-broker.mjs',
];

const CORE_DIRS = [
  'hub/pipeline',
  'hub/routing',
  'hub/quality',
  'hub/delegator',
  'hub/lib',
  'hub/middleware',
  'hub/workers/worker-utils.mjs', // shared utility
];

const REMOTE_FILES = [
  'hub/server.mjs',
  'hub/store.mjs',
  'hub/store-adapter.mjs',
  'hub/pipe.mjs',
  'hub/tools.mjs',
  'hub/tray.mjs',
];

const REMOTE_DIRS = [
  'hub/team',
  'hub/workers',
  'hub/public',
];

const TRIFLUX_DIRS = [
  'bin',
  'skills',
];

const TRIFLUX_FILES = [
  'README.md',
  'README.ko.md',
  'LICENSE',
];

// ── 복사 유틸 ───────────────────────────────────────────────────

function copyItem(src, dest) {
  const fullSrc = join(ROOT, src);
  if (!existsSync(fullSrc)) {
    console.warn(`  SKIP ${src} (not found)`);
    return;
  }
  const fullDest = join(dest, src);
  mkdirSync(dirname(fullDest), { recursive: true });
  cpSync(fullSrc, fullDest, { recursive: true });
  console.log(`  COPY ${src}`);
}

function cleanDist(pkgDir) {
  const dirs = ['hub', 'bin', 'skills', 'scripts', 'hooks', 'hud'];
  for (const d of dirs) {
    const target = join(pkgDir, d);
    if (existsSync(target)) rmSync(target, { recursive: true, force: true });
  }
  for (const f of ['README.md', 'README.ko.md', 'LICENSE']) {
    const target = join(pkgDir, f);
    if (existsSync(target) && target !== join(ROOT, f)) rmSync(target, { force: true });
  }
}

// ── Cross-package import 리라이팅 ────────────────────────────────

function walkMjs(dir) {
  const files = [];
  if (!existsSync(dir)) return files;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) files.push(...walkMjs(full));
    else if (entry.name.endsWith('.mjs')) files.push(full);
  }
  return files;
}

function buildFileSet(baseDir) {
  const files = new Set();
  if (!existsSync(baseDir)) return files;
  for (const f of walkMjs(baseDir)) {
    files.add(normalize(f));
  }
  return files;
}

/**
 * remote 패키지 내 .mjs 파일에서 core 모듈을 참조하는 상대 import를
 * @triflux/core 패키지 경로로 리라이팅한다.
 */
function rewriteRemoteImports(remotePkgDir, corePkgDir) {
  const coreFiles = buildFileSet(corePkgDir);
  let totalRewrites = 0;

  for (const filePath of walkMjs(remotePkgDir)) {
    let content = readFileSync(filePath, 'utf8');
    let changed = false;

    content = content.replace(
      /(from\s+['"])(\.[^'"]+)(['"])/g,
      (match, pre, importPath, post) => {
        const resolved = normalize(join(dirname(filePath), importPath));
        // import 대상이 remote 패키지 내에 있으면 그대로 유지
        if (existsSync(resolved)) return match;
        // core 패키지에 동일 상대경로로 존재하는지 확인
        const relToRemote = relative(remotePkgDir, resolved).replace(/\\/g, '/');
        const coreEquiv = normalize(join(corePkgDir, relToRemote));
        if (coreFiles.has(coreEquiv)) {
          changed = true;
          totalRewrites++;
          return `${pre}@triflux/core/${relToRemote}${post}`;
        }
        return match;
      }
    );

    if (changed) writeFileSync(filePath, content);
  }

  return totalRewrites;
}

// ── Index 생성 ──────────────────────────────────────────────────

const CORE_INDEX = `// @triflux/core — barrel export (auto-generated by pack.mjs)
// Adapters
export { buildExecCommand, sleep, gte, FEATURES, CODEX_MCP_TRANSPORT_EXIT_CODE, normalizePathForShell, shellQuote } from './cli-adapter-base.mjs';
export { execute as executeCodex, buildExecArgs as buildCodexArgs, buildLaunchScript, getCircuitState as getCodexCircuit } from './codex-adapter.mjs';
export { execute as executeGemini, buildExecArgs as buildGeminiArgs, getCircuitState as getGeminiCircuit } from './gemini-adapter.mjs';
export { getCodexVersion, runPreflight } from './codex-preflight.mjs';

// Routing & Intent
export { createRouter } from './router.mjs';
export { classifyIntent, quickClassify, INTENT_CATEGORIES, refineClassification } from './intent.mjs';

// State & Paths & Platform
export * from './paths.mjs';
export { IS_WINDOWS, IS_MAC, IS_LINUX, TEMP_DIR, normalizePath, whichCommand, killProcess, pipePath } from './platform.mjs';

// Core services
export { createHitlManager } from './hitl.mjs';
export { createAssignCallbackServer } from './assign-callbacks.mjs';
export { getHubUrl, getHubPipePath, requestJson, post, connectPipe, parseArgs, parseJsonSafe } from './bridge.mjs';

// Fullcycle & Research
export { createFullcycleRunId, getFullcycleRunDir, ensureFullcycleRunDir, saveFullcycleArtifact, readFullcycleArtifact, writeFullcycleState, readFullcycleState, shouldStopQaLoop } from './fullcycle.mjs';
export { generateQueries, normalizeResults, buildReport, saveReport } from './research.mjs';

// Reflexion (adaptive error learning)
export { normalizeError, lookupSolution, learnFromError, reportOutcome, adaptiveRuleFromError, getActiveAdaptiveRules } from './reflexion.mjs';

// Neural Memory (Lake 1.5)
export { createAdaptiveEngine } from './adaptive.mjs';
export { createAdaptiveMemory } from './adaptive-memory.mjs';
export { createDiagnosticPipeline } from './adaptive-diagnostic.mjs';
export { createAdaptiveInjector } from './adaptive-inject.mjs';
export { buildAdaptiveFingerprint, createAdaptiveFingerprintService } from './session-fingerprint.mjs';
export { broker as accountBroker } from './account-broker.mjs';
`;

const REMOTE_INDEX = `// @triflux/remote — barrel export (auto-generated by pack.mjs)
// Server
export { startHub, getHubInfo, getOrCreateServer } from './server.mjs';

// Store
export { createStoreAdapter } from './store-adapter.mjs';

// Pipe
export { createPipeServer, getPipePath } from './pipe.mjs';

// Team
export { orchestrate, decomposeTask, buildLeadPrompt, buildPrompt } from './team/orchestrator.mjs';
export { createPsmuxSession, startCapture } from './team/psmux.mjs';
export { createConductor } from './team/conductor.mjs';

// Swarm
export { createSwarmLocks } from './team/swarm-locks.mjs';
export { parseShards, buildFileLeaseMap, buildMcpManifest, computeMergeOrder, planSwarm } from './team/swarm-planner.mjs';
export { createSwarmHypervisor, SWARM_STATES } from './team/swarm-hypervisor.mjs';
export { reconcile, buildRedundantIds, shouldRunRedundant } from './team/swarm-reconciler.mjs';
export { ensureWorktree, prepareIntegrationBranch, rebaseShardOntoIntegration, pruneWorktree } from './team/worktree-lifecycle.mjs';
`;

function writeIndex(dest, content) {
  const indexPath = join(dest, 'hub', 'index.mjs');
  writeFileSync(indexPath, content);
  console.log('  WRITE hub/index.mjs');
}

// ── Pack 함수 ───────────────────────────────────────────────────

function packCore() {
  const dest = join(ROOT, 'packages', 'core');
  console.log('\n@triflux/core');
  cleanDist(dest);
  for (const f of CORE_FILES) copyItem(f, dest);
  for (const d of CORE_DIRS) copyItem(d, dest);
  // shared scripts/lib for logger, context
  copyItem('scripts/lib', dest);
  copyItem('hooks', dest);
  copyItem('hud', dest);
  writeIndex(dest, CORE_INDEX);
  console.log('  DONE');
}

function packRemote() {
  const dest = join(ROOT, 'packages', 'remote');
  const coreDest = join(ROOT, 'packages', 'core');
  console.log('\n@triflux/remote');
  cleanDist(dest);
  for (const f of REMOTE_FILES) copyItem(f, dest);
  for (const d of REMOTE_DIRS) copyItem(d, dest);
  // shared scripts/lib needed by delegator-mcp.mjs (dynamic resolve)
  copyItem('scripts/lib', dest);
  writeIndex(dest, REMOTE_INDEX);
  const rewrites = rewriteRemoteImports(dest, coreDest);
  console.log(`  REWROTE ${rewrites} cross-package imports → @triflux/core`);
  console.log('  DONE');
}

function packTriflux() {
  const dest = join(ROOT, 'packages', 'triflux');
  console.log('\ntriflux (meta)');
  cleanDist(dest);
  for (const f of TRIFLUX_FILES) copyItem(f, dest);
  for (const d of TRIFLUX_DIRS) copyItem(d, dest);
  console.log('  DONE');
}

// ── Main ────────────────────────────────────────────────────────

const target = process.argv[2] || 'all';

console.log(`pack: assembling packages (target=${target})`);
console.log(`root: ${ROOT}`);

if (target === 'core' || target === 'all') packCore();
if (target === 'remote' || target === 'all') packRemote();
if (target === 'triflux' || target === 'all') packTriflux();

console.log('\nPack complete. Run `npm pack` in each package to create tarballs.');
