#!/usr/bin/env node
// scripts/pack.mjs — 패키지 조립 스크립트
// 소스 파일을 packages/*/에 복사하여 npm publish 준비.
//
// Usage: node scripts/pack.mjs [core|remote|triflux|all]

import {
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, normalize, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));

// ── 파일 매핑: 패키지별로 어떤 소스 파일이 포함되는지 ──────────

const CORE_FILES = [
  // hub root — core modules
  "hub/cli-adapter-base.mjs",
  "hub/platform.mjs",
  "hub/bridge.mjs",
];

const CORE_DIRS = [
  "hub/lib",
  "hub/team/intervention.mjs",
  // intervention 의 pane 채널이 동적 import 한다
  "hub/team/psmux.mjs",
  "hub/team/pane.mjs",
  // pane 이 CLI 이름을 실행 파일로 풀 때 읽는다
  "hub/team/agent-map.json",
  "hub/team/session.mjs",
  "hub/team/nativeProxy.mjs",
  "hub/team/retry-state-machine.mjs",
  "hub/team/claude-agent-session-normalizer.mjs",
  "hub/team/claude-daemon-control.mjs",
  "hub/team/claude-transcript.mjs",
  "hub/team/session-context.mjs",
  "hub/team/claude-session-projection.mjs",
  "hub/workers/worker-utils.mjs", // shared utility
];

// core 에 들어가는 전부. release:check-mirror 도 이 목록으로 검사한다.
export const CORE_ENTRIES = [
  ...CORE_FILES,
  ...CORE_DIRS,
  "scripts/lib",
  "hooks",
  "hud",
];

const REMOTE_DIRS = ["hub/team", "hub/workers"];

const TRIFLUX_DIRS = [
  "adapters",
  "bin",
  "skills",
  "hooks",
  "hud",
  "scripts",
  "hub",
];

// CLAUDE.md 는 저장소 운영 지침이라 게시본에 넣지 않는다.
const TRIFLUX_FILES = ["README.md", "README.ko.md", "LICENSE"];

// ── 복사 유틸 ───────────────────────────────────────────────────

function copyItem(src, dest) {
  const fullSrc = join(ROOT, src);
  if (!existsSync(fullSrc)) {
    console.warn(`  SKIP ${src} (not found)`);
    return;
  }
  const fullDest = join(dest, src);
  mkdirSync(dirname(fullDest), { recursive: true });
  cpSync(fullSrc, fullDest, { recursive: true });
  console.log(`  COPY ${src}`);
}

function cleanDist(pkgDir) {
  const dirs = ["hub", "bin", "skills", "scripts", "hooks", "hud", "cto"];
  for (const d of dirs) {
    const target = join(pkgDir, d);
    if (existsSync(target)) rmSync(target, { recursive: true, force: true });
  }
  for (const f of ["README.md", "README.ko.md", "LICENSE"]) {
    const target = join(pkgDir, f);
    if (existsSync(target) && target !== join(ROOT, f))
      rmSync(target, { force: true });
  }
}

// ── Cross-package import 리라이팅 ────────────────────────────────

function walkMjs(dir) {
  const files = [];
  if (!existsSync(dir)) return files;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) files.push(...walkMjs(full));
    else if (entry.name.endsWith(".mjs")) files.push(full);
  }
  return files;
}

function buildFileSet(baseDir) {
  const files = new Set();
  if (!existsSync(baseDir)) return files;
  for (const f of walkMjs(baseDir)) {
    files.add(normalize(f));
  }
  return files;
}

/**
 * remote 패키지 내 .mjs 파일에서 core 모듈을 참조하는 상대 import를
 * @triflux/core 패키지 경로로 리라이팅한다.
 */
function rewriteRemoteImports(remotePkgDir, corePkgDir) {
  const coreFiles = buildFileSet(corePkgDir);
  let totalRewrites = 0;

  for (const filePath of walkMjs(remotePkgDir)) {
    let content = readFileSync(filePath, "utf8");
    let changed = false;

    const rewriteRelativeSpecifier = (match, pre, importPath, post) => {
      const resolved = normalize(join(dirname(filePath), importPath));
      // import 대상이 remote 패키지 내에 있으면 그대로 유지
      if (existsSync(resolved)) return match;
      // core 패키지에 동일 상대경로로 존재하는지 확인
      const relToRemote = relative(remotePkgDir, resolved).replace(/\\/g, "/");
      const coreEquiv = normalize(join(corePkgDir, relToRemote));
      if (coreFiles.has(coreEquiv)) {
        changed = true;
        totalRewrites++;
        return `${pre}@triflux/core/${relToRemote}${post}`;
      }
      return match;
    };

    content = content.replace(
      /(from\s+['"])(\.[^'"]+)(['"])/g,
      rewriteRelativeSpecifier,
    );
    content = content.replace(
      /(import\(\s*['"])(\.[^'"]+)(['"]\s*\))/g,
      rewriteRelativeSpecifier,
    );

    if (changed) writeFileSync(filePath, content);
  }

  return totalRewrites;
}

// ── Index 생성 ──────────────────────────────────────────────────

const CORE_INDEX = `// @triflux/core — barrel export (auto-generated by pack.mjs)
// Platform
export { IS_WINDOWS, IS_MAC, IS_LINUX, TEMP_DIR, normalizePath, whichCommand, killProcess, pipePath } from './platform.mjs';

// Core services
export { parseArgs, parseJsonSafe } from './bridge.mjs';
`;

const REMOTE_INDEX = `// @triflux/remote — barrel export (auto-generated by pack.mjs)
// Team
export { orchestrate, decomposeTask, buildLeadPrompt, buildPrompt } from './team/orchestrator.mjs';
export { createPsmuxSession, startCapture } from './team/psmux.mjs';
`;

function writeIndex(dest, content) {
  const indexPath = join(dest, "hub", "index.mjs");
  writeFileSync(indexPath, content);
  console.log("  WRITE hub/index.mjs");
}

// ── Pack 함수 ───────────────────────────────────────────────────

function packCore() {
  const dest = join(ROOT, "packages", "core");
  console.log("\n@triflux/core");
  cleanDist(dest);
  for (const entry of CORE_ENTRIES) copyItem(entry, dest);
  writeIndex(dest, CORE_INDEX);
  console.log("  DONE");
}

function packRemote() {
  const dest = join(ROOT, "packages", "remote");
  const coreDest = join(ROOT, "packages", "core");
  console.log("\n@triflux/remote");
  cleanDist(dest);
  for (const d of REMOTE_DIRS) copyItem(d, dest);
  // hub/team 이 쓰는 공용 scripts/lib
  copyItem("scripts/lib", dest);
  writeIndex(dest, REMOTE_INDEX);
  const rewrites = rewriteRemoteImports(dest, coreDest);
  console.log(`  REWROTE ${rewrites} cross-package imports → @triflux/core`);
  console.log("  DONE");
}

function packTriflux() {
  const dest = join(ROOT, "packages", "triflux");
  console.log("\ntriflux (meta)");
  cleanDist(dest);
  // clean extra dirs that triflux now includes. cto, references 는 싣지 않지만 옛 사본을 지우려고 남긴다.
  for (const d of [
    "adapters",
    "hooks",
    "hud",
    "scripts",
    "hub",
    "cto",
    "references",
  ]) {
    const target = join(dest, d);
    if (existsSync(target)) rmSync(target, { recursive: true, force: true });
  }
  for (const f of TRIFLUX_FILES) copyItem(f, dest);
  for (const d of TRIFLUX_DIRS) copyItem(d, dest);
  console.log("  DONE");
}

// ── Main ────────────────────────────────────────────────────────

// 목록만 읽으려고 import 할 때는 조립하지 않는다.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const target = process.argv[2] || "all";

  console.log(`pack: assembling packages (target=${target})`);
  console.log(`root: ${ROOT}`);

  if (target === "core" || target === "all") packCore();
  if (target === "remote" || target === "all") packRemote();
  if (target === "triflux" || target === "all") packTriflux();

  console.log(
    "\nPack complete. Run `npm pack` in each package to create tarballs.",
  );
}
