// ADR-0021 회귀 가드: 키워드 훅을 명시 호출 중심으로 줄이고 자연어는 suggest 로 낮춘다.
// 오탐·정탐 예시는 두 머신(m2·m5) 60일 감사 코퍼스의 대표 사례를 개인정보·고객사 정보
// 없는 일반 문장으로 바꾼 것이다.
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { after, describe, it } from "node:test";
import {
  isAutoGeneratedPrompt,
  isShortReaction,
  isSlashCommandPrompt,
  resolveInstalledSkill,
  sanitizeForKeywordDetection,
  stripPastedContent,
} from "../../scripts/keyword-detector.mjs";
import {
  compileRules,
  loadRules,
  matchRules,
} from "../../scripts/lib/keyword-rules.mjs";

const ROOT = process.cwd();
const DETECTOR = join(ROOT, "scripts", "keyword-detector.mjs");

const tempDirs = [];
function tempDir() {
  const dir = mkdtempSync(join(tmpdir(), "kw-audit-"));
  tempDirs.push(dir);
  return dir;
}
after(() => {
  for (const dir of tempDirs) rmSync(dir, { recursive: true, force: true });
});

// gstack 스킬 설치 이름을 흉내 내는 임시 스킬 루트 (접두사 없음 / 있음).
function skillRoot(names) {
  const root = tempDir();
  for (const name of names) {
    mkdirSync(join(root, name), { recursive: true });
    writeFileSync(join(root, name, "SKILL.md"), `---\nname: ${name}\n---\n`);
  }
  return root;
}
const PLAIN_GSTACK = skillRoot(["ship", "retro", "context-restore"]);
// triflux repo_scope 판정용 cwd (path segment 에 triflux 포함).
const TRIFLUX_CWD = join(ROOT, "..", "triflux", "work");

function runDetector(prompt, env = {}, cwd = ROOT) {
  const result = spawnSync(process.execPath, [DETECTOR], {
    input: JSON.stringify({ prompt, cwd }),
    encoding: "utf8",
    env: {
      ...process.env,
      TRIFLUX_DISABLE_MAGICWORDS: "",
      TRIFLUX_SKILL_ROOTS: PLAIN_GSTACK,
      ...env,
    },
  });
  assert.equal(result.status, 0, result.stderr);
  return JSON.parse(result.stdout.trim());
}

function contextOf(prompt, env, cwd) {
  return runDetector(prompt, env, cwd)?.hookSpecificOutput?.additionalContext;
}

function writeRules(rules) {
  const file = join(tempDir(), "rules.json");
  writeFileSync(file, JSON.stringify({ rules }), "utf8");
  return file;
}

describe("감사 대표 오탐은 주입하지 않는다", () => {
  for (const prompt of [
    "진행해",
    "일정은 어떻지?",
    "You have new mail",
    "/resume",
    "/chrome",
    "/tfx-auto 로그인 기능 구현해줘",
    [
      "이 목록 봐",
      '<pasted_content id="1">',
      "- tfx-auto: 구현·수정 요청에 사용",
      "- tfx-ship: 릴리즈 해줘 같은 요청에 사용",
      "- 코드 리뷰해줘, 버그 고쳐줘",
      '</pasted_content id="1">',
    ].join("\n"),
    "> 로그인 기능 구현해줘\n위 인용은 어제 메모야",
    "릴리즈 되나?",
    "코드 구현해도 될까?",
    // m5: 다른 에이전트가 만든 핸드오프·리드·중계 프롬프트
    "Continuation skills: tfx-auto, tfx-review\n- 결제 모듈 버그 고쳐줘\n- 테스트 코드 추가해줘",
    "- Handoff envelope\n이전 세션에서 함수 구현해줘 요청을 이어받는다",
    "리드 에이전트: 워커에게 설정 파일 수정해 달라고 지시한다",
    "SESSION_RELAY: 로그인 화면 버튼 고쳐줘 라는 요청이 왔다",
    // m5: 스킬 선언 목록 줄
    "아래 중에 골라서 써\n- /tfx-auto — 코드 구현해줘 같은 요청\n- /tfx-ship — 릴리즈 해줘 같은 요청\n어느 쪽이 맞는지만 말해",
    // m5: 짧은 반응·질문·다른 도메인
    "좋아 진행해",
    "지금 이 상태로 배포해도 되나?",
    "회고 템플릿 찾아서 써줄래 그리고 공유해",
    "크롬 설정은 나눠서 하나씩 말해줘",
    "이 발표 대본 문구를 명사형으로 바꿔줘",
  ]) {
    it(JSON.stringify(prompt.slice(0, 30)), () => {
      const output = runDetector(prompt);
      assert.equal(output.suppressOutput, true);
      assert.equal(output.hookSpecificOutput, undefined);
    });
  }
});

describe("감사 정탐은 유지한다", () => {
  // 공백 제외 12자 이하는 짧은 반응 가드(E)가 거르므로 정탐 예시는 그보다 길다.
  for (const prompt of [
    "결제 화면에 로그인 기능 구현해줘",
    "목록 정렬하는 이 함수 버그 좀 고쳐줘",
    "implement the parser",
    "스킬에 버그가 있었다면 직접 수정해줘",
  ]) {
    it(`${prompt} → tfx-auto suggest`, () => {
      const context = contextOf(prompt);
      assert.match(context, /^\[TRIFLUX SKILL SUGGESTION: tfx-unified\]/);
      assert.match(
        context,
        /코드 구현·수정 실행 요청이면 Skill 도구로 tfx-auto/,
      );
      assert.match(context, /질문·상태 확인·대화·다른 도메인이면/);
      assert.doesNotMatch(context, /MUST/);
    });
  }

  it("이 작업 tfx-auto 로 돌려줘 → MUST 호출", () => {
    const context = contextOf("이 작업 tfx-auto 로 돌려줘");
    assert.match(context, /^\[TRIFLUX MAGIC KEYWORD: tfx-unified\]/);
    assert.match(context, /You MUST invoke the skill/);
    assert.match(context, /Skill: tfx-auto/);
  });

  it("문장 중간 /tfx-harness 는 MUST 호출 (호스트가 확장하지 않는다)", () => {
    const context = contextOf(
      "이번 건은 /tfx-harness 로 어떤 경로가 맞는지 판정해줘",
    );
    assert.match(context, /^\[TRIFLUX MAGIC KEYWORD: tfx-harness\]/);
    assert.match(context, /Skill: tfx-harness/);
  });

  it("짧아도 문장 중간 /tfx- 토큰이 있으면 짧은 반응으로 보지 않는다", () => {
    assert.match(contextOf("그럼 /tfx-auto 로"), /Skill: tfx-auto/);
  });

  it("슬래시 없는 이름 언급은 주입하지 않는다", () => {
    for (const prompt of [
      "그건 이미 tfx-auto에 합쳐졌을텐데 맞지",
      "tfx-harness? tfx-auto? 뭐가 기본 진입점이었더라",
    ]) {
      assert.equal(contextOf(prompt), undefined, prompt);
    }
  });

  it("triflux repo 에서 버전 올려서 릴리즈하고 → tfx-ship 제안", () => {
    const context = contextOf(
      "버전 올려서 릴리즈하고 로컬에도 반영해줘",
      {},
      TRIFLUX_CWD,
    );
    assert.match(context, /^\[TRIFLUX SKILL SUGGESTION: tfx-ship\]/);
  });

  it("주입문은 프롬프트 원문과 OMC 무시 지시를 싣지 않는다", () => {
    for (const prompt of [
      "이 작업 tfx-auto 로 돌려줘",
      "결제 화면에 로그인 기능 구현해줘",
    ]) {
      const context = contextOf(prompt);
      assert.doesNotMatch(context, /User request:/);
      assert.ok(!context.includes(prompt), "프롬프트 원문이 다시 붙었습니다");
      assert.doesNotMatch(context, /\[MAGIC KEYWORD:\]/);
      assert.doesNotMatch(context, /PRIORITY:/);
    }
  });
});

describe("isSlashCommandPrompt", () => {
  for (const text of [
    "/resume",
    "  /oh-my-claudecode:team 3",
    "/loop 5m /foo",
    "/context-restore\n이어서",
    "/multilingual-parallel-research:research-run",
  ]) {
    it(`${JSON.stringify(text)} → true`, () => {
      assert.equal(isSlashCommandPrompt(text), true);
    });
  }
  for (const text of [
    "/Users/me/project 의 함수 고쳐줘",
    "tfx-auto /resume 같이",
    "",
    null,
  ]) {
    it(`${JSON.stringify(text)} → false`, () => {
      assert.equal(isSlashCommandPrompt(text), false);
    });
  }
});

describe("자동 생성·짧은 반응 가드", () => {
  it("isAutoGeneratedPrompt: 핸드오프·리드·대문자 태그 봉투", () => {
    for (const text of [
      "Continuation skills: a, b",
      "  Continuation contract — keep going",
      "- Handoff envelope v2",
      "리드 에이전트: 워커 배치",
      "TOPIC_RELAY: hello",
      "앞부분\nContinuation contract: 유지",
    ]) {
      assert.equal(isAutoGeneratedPrompt(text), true, text);
    }
    for (const text of [
      "로그인 기능 구현해줘",
      "README 고쳐줘",
      "API 키 확인",
    ]) {
      assert.equal(isAutoGeneratedPrompt(text), false, text);
    }
  });

  it("isShortReaction: 공백 제외 12자 이하, 문장 중간 /tfx- 토큰은 예외", () => {
    assert.equal(isShortReaction("진행해"), true);
    assert.equal(isShortReaction("좋아 그대로 진행해 줘"), true);
    assert.equal(isShortReaction("결제 화면에 로그인 기능 구현해줘"), false);
    assert.equal(isShortReaction("그럼 /tfx-auto"), false);
    assert.equal(isShortReaction("a/tfx-auto"), true);
  });

  it("stripPastedContent: 붙여넣기 블록을 빼고 직접 친 텍스트만 남긴다", () => {
    assert.equal(
      stripPastedContent(
        '봐줘 <pasted_content id="2">\nContinuation skills: x\n</pasted_content id="2"> 끝',
      ),
      "봐줘   끝",
    );
  });
});

describe("sanitizeForKeywordDetection 보강", () => {
  it("스킬 선언 목록 줄(- /tfx-x — 설명)을 지운다", () => {
    assert.equal(
      sanitizeForKeywordDetection(
        "목록\n- /tfx-auto — 코드 구현해줘\n* /tfx-ship - 릴리즈 해줘\n끝",
      ),
      "목록 끝",
    );
  });

  it("속성 달린 닫는 태그 짝을 지운다", () => {
    assert.equal(
      sanitizeForKeywordDetection(
        'a <pasted_content id="7">tfx-auto</pasted_content id="7"> b',
      ),
      "a b",
    );
  });

  it("~/ 경로를 지운다", () => {
    assert.equal(
      sanitizeForKeywordDetection("열어봐 ~/work/tfx-ship/notes.md 지금"),
      "열어봐 지금",
    );
  });

  it("줄 머리 > 인용문을 지우고 줄 중간 > 는 남긴다", () => {
    assert.equal(
      sanitizeForKeywordDetection("> 인용\n  >> 중첩 인용\na > b"),
      "a > b",
    );
  });
});

describe("exclude_patterns / strength 규칙 필드", () => {
  const fixture = () =>
    writeRules([
      {
        id: "mixed",
        patterns: [
          { source: "\\bfoo-skill\\b", flags: "i", strength: "explicit" },
          { source: "바꿔", flags: "" },
        ],
        exclude_patterns: [{ source: "[?]\\s*$", flags: "" }],
        skill: "foo-skill",
        priority: 1,
        strength: "suggest",
        suggest_when: "푸 작업 실행 요청",
      },
      {
        id: "plain",
        patterns: [{ source: "bar", flags: "i" }],
        skill: "bar-skill",
        priority: 2,
      },
    ]);

  it("규칙 기본 strength 는 explicit, 패턴별 strength 가 덮어쓴다", () => {
    const rules = loadRules(fixture());
    const mixed = rules.find((r) => r.id === "mixed");
    assert.equal(mixed.strength, "suggest");
    assert.deepEqual(
      mixed.patterns.map((p) => p.strength),
      ["explicit", "suggest"],
    );
    assert.equal(rules.find((r) => r.id === "plain").strength, "explicit");
  });

  it("suggest 매칭은 exclude_patterns 에 걸리면 빠진다", () => {
    const compiled = compileRules(loadRules(fixture()));
    assert.equal(matchRules(compiled, "이거 바꿔")[0]?.strength, "suggest");
    assert.deepEqual(matchRules(compiled, "이거 바꿔?"), []);
  });

  it("명시 토큰 매칭은 exclude_patterns 와 무관하게 explicit 로 남는다", () => {
    const compiled = compileRules(loadRules(fixture()));
    const [match] = matchRules(compiled, "foo-skill 로 바꿔?");
    assert.equal(match?.id, "mixed");
    assert.equal(match?.strength, "explicit");
  });

  it("잘못된 strength·exclude_patterns 는 규칙을 무효로 본다", () => {
    const file = writeRules([
      {
        id: "bad-strength",
        patterns: [{ source: "a", flags: "" }],
        skill: "x",
        priority: 1,
        strength: "must",
      },
      {
        id: "bad-exclude",
        patterns: [{ source: "a", flags: "" }],
        exclude_patterns: "nope",
        skill: "x",
        priority: 1,
      },
      {
        id: "ok",
        patterns: [{ source: "a", flags: "" }],
        skill: "x",
        priority: 1,
      },
    ]);
    assert.deepEqual(
      loadRules(file).map((r) => r.id),
      ["ok"],
    );
  });

  it("suggest 주입문은 suggest_when 을 조건으로 쓴다", () => {
    const context = contextOf("이 문단 전체를 조금 더 다른 말로 바꿔", {
      TRIFLUX_KEYWORD_RULES_PATH: fixture(),
    });
    assert.match(context, /^\[TRIFLUX SKILL SUGGESTION: mixed\]/);
    assert.match(context, /푸 작업 실행 요청이면 Skill 도구로 foo-skill/);
  });

  it("context_hint 주입문에 Windows 전용 wt.exe 문구가 붙지 않는다", () => {
    const file = writeRules([
      {
        id: "hint-rule",
        patterns: [{ source: "hinty-keyword", flags: "i" }],
        action: "context_hint",
        hint: "범용 힌트",
        priority: 1,
      },
    ]);
    const context = contextOf("please apply hinty-keyword now", {
      TRIFLUX_KEYWORD_RULES_PATH: file,
    });
    assert.equal(context, "[TRIFLUX CONTEXT HINT: hint-rule]\n\n범용 힌트");
  });
});

describe("hooks/keyword-rules.json 감사 반영", () => {
  const rules = loadRules(join(ROOT, "hooks", "keyword-rules.json"));

  it("맨명사 MCP 라우트·handoff·사용 0회 토큰 규칙이 없다", () => {
    const ids = new Set(rules.map((r) => r.id));
    for (const id of [
      "chrome-route",
      "mail-route",
      "calendar-route",
      "github-route",
      "confluence-route",
      "notion-route",
      "jira-route",
      "slack-route",
      "playwright-route",
      "canva-route",
      "handoff-route",
      "tfx-analysis",
      "tfx-prune",
      "tfx-hub",
    ]) {
      assert.equal(ids.has(id), false, `${id} 가 남아 있다`);
    }
  });

  it("gstack-checkpoint 는 실제 스킬 이름 context-restore 를 가리키고 맨 resume 을 잡지 않는다", () => {
    const rule = rules.find((r) => r.id === "gstack-checkpoint");
    assert.deepEqual(rule.skill_candidates, [
      "context-restore",
      "gstack-context-restore",
    ]);
    const compiled = compileRules(rules);
    assert.equal(
      matchRules(compiled, "resume the download").some(
        (m) => m.id === "gstack-checkpoint",
      ),
      false,
    );
  });

  it("host-ai-slop-cleaner 는 맨 '클린업'·'슬롭'을 잡지 않는다", () => {
    const compiled = compileRules(rules);
    for (const text of ["클린업 해줘", "슬롭 정리"]) {
      assert.equal(
        matchRules(compiled, text).some((m) => m.id === "host-ai-slop-cleaner"),
        false,
        text,
      );
    }
  });

  it("suppress-omc-team 은 맨 '팀' 을 잡지 않는다", () => {
    const compiled = compileRules(rules);
    for (const text of [
      "우리 팀 회의",
      "팀장님 메일",
      "레드팀으로 공격 시나리오 짜보자",
      "개발팀 구성 현황 알려줘",
      "팀 저장소 구성 정리",
      "이건 /team 으로 돌려",
    ]) {
      assert.equal(
        matchRules(compiled, text).some((m) => m.id === "suppress-omc-team"),
        false,
        text,
      );
    }
    assert.ok(
      matchRules(compiled, "팀 모드로 돌려").some(
        (m) => m.id === "suppress-omc-team",
      ),
    );
  });
});

describe("gstack 스킬 설치 이름 해석 (머신별 접두사)", () => {
  it("resolveInstalledSkill: 후보 중 설치된 첫 이름, 없으면 null", () => {
    const prefixed = skillRoot(["gstack-ship"]);
    assert.equal(
      resolveInstalledSkill(["ship", "gstack-ship"], [PLAIN_GSTACK]),
      "ship",
    );
    assert.equal(
      resolveInstalledSkill(["ship", "gstack-ship"], [prefixed]),
      "gstack-ship",
    );
    assert.equal(
      resolveInstalledSkill(["ship", "gstack-ship"], [tempDir()]),
      null,
    );
  });

  const retroPrompt = "이번 주 회고 해보자 뭐가 잘 됐는지 정리해서";

  it("접두사 설치 머신에서는 gstack-retro 로 주입한다", () => {
    const context = contextOf(retroPrompt, {
      TRIFLUX_SKILL_ROOTS: skillRoot(["gstack-retro"]),
    });
    assert.match(context, /Skill 도구로 gstack-retro 을 고려하라/);
  });

  it("접두사 없는 머신에서는 retro 로 주입한다", () => {
    assert.match(contextOf(retroPrompt), /Skill 도구로 retro 을 고려하라/);
  });

  it("후보가 하나도 설치되지 않았으면 주입하지 않는다", () => {
    assert.equal(
      contextOf(retroPrompt, { TRIFLUX_SKILL_ROOTS: tempDir() }),
      undefined,
    );
  });

  it("gstack-retro 는 회고 문서·회의 요청을 잡지 않는다", () => {
    for (const prompt of [
      "회고 템플릿 찾아서 이번 주 회고 문서 써줘",
      "지난 주 회고 회의 내용 전사해줘",
    ]) {
      assert.equal(contextOf(prompt), undefined, prompt);
    }
  });

  it("gstack-ship 은 맨 '배포해' 를 잡지 않고 PR 표현만 받는다", () => {
    const compiled = compileRules(
      loadRules(join(ROOT, "hooks", "keyword-rules.json")),
    );
    const ids = (t) => matchRules(compiled, t).map((m) => m.id);
    assert.ok(!ids("dev 서버에 배포해 봐").includes("gstack-ship"));
    assert.ok(ids("이 브랜치로 PR 올려줘").includes("gstack-ship"));
    assert.ok(ids("looks good, ship it").includes("gstack-ship"));
    assert.ok(!ids("PR 올려도 되나?").includes("gstack-ship"));
  });
});
