// @triflux/core — barrel export (auto-generated by pack.mjs)
// Adapters
export { buildExecCommand, sleep, CODEX_MCP_TRANSPORT_EXIT_CODE, normalizePathForShell, shellQuote } from './cli-adapter-base.mjs';
export { execute as executeCodex, buildExecArgs as buildCodexArgs, buildLaunchScript } from './codex-adapter.mjs';
export { getCodexVersion, runPreflight } from './codex-preflight.mjs';

// Platform
export { IS_WINDOWS, IS_MAC, IS_LINUX, TEMP_DIR, normalizePath, whichCommand, killProcess, pipePath } from './platform.mjs';

// Core services
export { parseArgs, parseJsonSafe } from './bridge.mjs';
