// @triflux/core — barrel export (auto-generated by pack.mjs)
// Adapters

export { broker as accountBroker } from "./account-broker.mjs";
// Neural Memory (Lake 1.5)
export { createAdaptiveEngine } from "./adaptive.mjs";
export { createDiagnosticPipeline } from "./adaptive-diagnostic.mjs";
export { createAdaptiveInjector } from "./adaptive-inject.mjs";
export { createAdaptiveMemory } from "./adaptive-memory.mjs";
export { createAssignCallbackServer } from "./assign-callbacks.mjs";
export {
  connectPipe,
  getHubPipePath,
  getHubUrl,
  parseArgs,
  parseJsonSafe,
  post,
  requestJson,
} from "./bridge.mjs";
export {
  buildExecCommand,
  CODEX_MCP_TRANSPORT_EXIT_CODE,
  FEATURES,
  gte,
  normalizePathForShell,
  shellQuote,
  sleep,
} from "./cli-adapter-base.mjs";
export {
  buildExecArgs as buildCodexArgs,
  buildLaunchScript,
  execute as executeCodex,
  getCircuitState as getCodexCircuit,
} from "./codex-adapter.mjs";
export { getCodexVersion, runPreflight } from "./codex-preflight.mjs";
// Fullcycle & Research
export {
  createFullcycleRunId,
  ensureFullcycleRunDir,
  getFullcycleRunDir,
  readFullcycleArtifact,
  readFullcycleState,
  saveFullcycleArtifact,
  shouldStopQaLoop,
  writeFullcycleState,
} from "./fullcycle.mjs";
export {
  buildExecArgs as buildGeminiArgs,
  execute as executeGemini,
  getCircuitState as getGeminiCircuit,
} from "./gemini-adapter.mjs";
// Core services
export { createHitlManager } from "./hitl.mjs";
export {
  classifyIntent,
  INTENT_CATEGORIES,
  quickClassify,
  refineClassification,
} from "./intent.mjs";
// State & Paths & Platform
export * from "./paths.mjs";
export {
  IS_LINUX,
  IS_MAC,
  IS_WINDOWS,
  killProcess,
  normalizePath,
  pipePath,
  TEMP_DIR,
  whichCommand,
} from "./platform.mjs";
// Reflexion (adaptive error learning)
export {
  adaptiveRuleFromError,
  getActiveAdaptiveRules,
  learnFromError,
  lookupSolution,
  normalizeError,
  reportOutcome,
} from "./reflexion.mjs";
export {
  buildReport,
  generateQueries,
  normalizeResults,
  saveReport,
} from "./research.mjs";
// Routing & Intent
export { createRouter } from "./router.mjs";
export {
  buildAdaptiveFingerprint,
  createAdaptiveFingerprintService,
} from "./session-fingerprint.mjs";
