// @triflux/core — barrel export (auto-generated by pack.mjs)
// Adapters
export { buildExecCommand, sleep, gte, FEATURES, CODEX_MCP_TRANSPORT_EXIT_CODE, normalizePathForShell, shellQuote } from './cli-adapter-base.mjs';
export { execute as executeCodex, buildExecArgs as buildCodexArgs, buildLaunchScript, getCircuitState as getCodexCircuit } from './codex-adapter.mjs';
export { execute as executeGemini, buildExecArgs as buildGeminiArgs, getCircuitState as getGeminiCircuit } from './gemini-adapter.mjs';
export { getCodexVersion, runPreflight } from './codex-preflight.mjs';

// Routing & Intent
export { createRouter } from './router.mjs';
export { classifyIntent, quickClassify, INTENT_CATEGORIES, refineClassification } from './intent.mjs';

// State & Paths & Platform
export * from './paths.mjs';
export { IS_WINDOWS, IS_MAC, IS_LINUX, TEMP_DIR, normalizePath, whichCommand, killProcess, pipePath } from './platform.mjs';

// Core services
export { createHitlManager } from './hitl.mjs';
export { createAssignCallbackServer } from './assign-callbacks.mjs';
export { getHubUrl, getHubPipePath, requestJson, post, connectPipe, parseArgs, parseJsonSafe } from './bridge.mjs';

// Fullcycle & Research
export { createFullcycleRunId, getFullcycleRunDir, ensureFullcycleRunDir, saveFullcycleArtifact, readFullcycleArtifact, writeFullcycleState, readFullcycleState, shouldStopQaLoop } from './fullcycle.mjs';
export { generateQueries, normalizeResults, buildReport, saveReport } from './research.mjs';

// Reflexion (adaptive error learning)
export { normalizeError, lookupSolution, learnFromError, reportOutcome, adaptiveRuleFromError, getActiveAdaptiveRules } from './reflexion.mjs';

// Neural Memory (Lake 1.5)
export { createAdaptiveEngine } from './adaptive.mjs';
export { createAdaptiveMemory } from './adaptive-memory.mjs';
export { createDiagnosticPipeline } from './adaptive-diagnostic.mjs';
export { createAdaptiveInjector } from './adaptive-inject.mjs';
export { buildAdaptiveFingerprint, createAdaptiveFingerprintService } from './session-fingerprint.mjs';
export { broker as accountBroker } from './account-broker.mjs';
